In [1]:
from quartic_sdk import APIClient
from quartic_sdk.core.entity_helpers.entity_list import EntityList
import os

client = APIClient(os.environ.get('QUARTIC_HOST'), username=os.environ.get('QUARTIC_USERNAME'), password=os.environ.get('QUARTIC_PASSWORD'))

### Asset

In [2]:
#Entity List of all available assests
assets=client.assets()
print("First 5 asssets from EntityList of available assets : \n" , assets[0:5])

#EntityList of required assets
asset1=assets.get("id",865)
asset2=assets.get("id",864)
asset_list = EntityList("Asset")
asset_list.add(asset1)
asset_list.add(asset2)
print("\nasset_list : ", asset_list)

#Get data of all tags of an asset between specified duration
asset1_data = asset1.data(start_time=1617086964262,stop_time=1617096964262)
print("\nasset1_data : ")
asset1_data[0] #Pandas df

First 5 asssets from EntityList of available assets :
 [<Asset: OPCDA_02_874>, <Asset: Asset CF Replay 03_869>, <Asset: Asset CF Replay 02_868>, <Asset: Asset CF Replay 01_867>, <Asset: Batch Automation Asset 001_865>]

asset_list :  <EntityList: [<Asset: Batch Automation Asset 001_865>, <Asset: OPCDA_01_864>, ]>

asset1_data :

,39936,39937,39938,39939,39940,39941,39942,39943,39944,39945,...,39926,39927,39928,39929,39930,39931,39932,39933,39934,39935
1617089520000,8.132487,11.870950,15.22221,28.349739,34.799530,15.49878,7.184520,3.592927,47.675289,47.709621,...,22.516020,35.141911,2.249180,22.550350,27.192909,29.967190,30.604259,15.65614,21.878000,14.62425
1617089580000,8.671321,11.441790,15.83638,27.278749,34.483860,12.63676,6.968033,3.668269,47.675289,47.709621,...,17.925920,35.534828,2.380789,22.653351,27.144279,29.271959,30.734909,14.58515,20.459869,14.76825
1617089640000,7.733845,10.696000,14.54509,27.082279,34.383732,13.65625,6.812582,3.591020,46.257149,47.709621,...,21.448839,34.601170,1.831464,21.810289,25.189211,29.965290,30.796900,15.15355,21.675819,13.53799
1617089700000,8.495842,10.741780,14.25994,25.977909,35.573929,13.79835,6.086824,3.806554,46.242840,47.709621,...,19.093229,33.637939,2.129969,20.916691,26.958300,29.342529,30.791180,16.15015,19.881929,14.38964
1617089760000,8.352789,11.973950,14.85504,30.230410,35.190552,14.38106,6.640917,3.677806,46.613831,47.709621,...,18.024151,34.275002,2.081331,21.724461,25.227360,30.291439,30.543221,16.42481,21.177999,13.04684
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1617096720000,7.829214,11.181430,14.79305,27.312120,34.450489,14.02914,6.416800,3.252461,47.219421,47.709621,...,20.744070,34.079498,2.341688,21.086439,28.200010,30.642401,31.288050,15.98516,22.822149,14.85886
1617096780000,6.871710,12.302010,15.85641,28.347830,35.131409,16.19879,6.280423,3.222897,46.626221,47.709621,...,19.446100,33.327030,2.058442,21.481270,26.261160,28.756010,31.410120,15.81636,22.015341,15.35096
1617096840000,7.830167,11.274890,14.30571,27.967310,34.544899,13.68486,5.900855,3.070306,46.909470,47.709621,...,18.414209,33.356602,2.159533,21.466009,27.799459,29.386400,30.825510,14.98093,22.894640,13.63336
1617096900000,7.375257,9.719425,15.28706,28.150419,34.510571,15.91363,6.406310,3.622492,46.755932,47.709621,...,20.871861,33.811508,1.881056,21.146521,26.914431,30.403980,30.910391,15.85832,21.539440,14.02724
1617096960000,8.581675,9.941634,14.48215,26.796181,34.966431,13.31960,6.744869,3.204776,47.565609,47.709621,...,19.120890,34.341759,1.869612,21.347750,27.020290,29.926180,30.888451,13.64099,18.580151,14.25994

### Tag

In [3]:
#EntityList of all tags of a particular Asset
tags = asset1.get_tags()
print("First 5 tags from EntityList of all available tags of asset1 : \n", tags[0:5])

#Get data of all tags in entitylist of tags between specified duration
tags_data = tags.data(start_time=1617086964262,stop_time=16170969642621)
print("\nTag data of all tags : ")
tags_data[0] #pandas df

First 5 tags from EntityList of all available tags of asset1 :
 [<Tag: DI-B3-10-4_39802>, <Tag: AI-7-71_39803>, <Tag: AI-13-10_39804>, <Tag: AI-13-19_39805>, <Tag: AI-13-11_39806>]

Tag data of all tags :

,39936,39937,39938,39939,39940,39941,39942,39943,39944,39945,...,39926,39927,39928,39929,39930,39931,39932,39933,39934,39935
1617089520000,8.132487,11.870950,15.22221,28.349739,34.799530,15.498780,7.184520,3.592927,47.675289,47.709621,...,22.516020,35.141911,2.249180,22.550350,27.192909,29.967190,30.604259,15.65614,21.878000,14.62425
1617089580000,8.671321,11.441790,15.83638,27.278749,34.483860,12.636760,6.968033,3.668269,47.675289,47.709621,...,17.925920,35.534828,2.380789,22.653351,27.144279,29.271959,30.734909,14.58515,20.459869,14.76825
1617089640000,7.733845,10.696000,14.54509,27.082279,34.383732,13.656250,6.812582,3.591020,46.257149,47.709621,...,21.448839,34.601170,1.831464,21.810289,25.189211,29.965290,30.796900,15.15355,21.675819,13.53799
1617089700000,8.495842,10.741780,14.25994,25.977909,35.573929,13.798350,6.086824,3.806554,46.242840,47.709621,...,19.093229,33.637939,2.129969,20.916691,26.958300,29.342529,30.791180,16.15015,19.881929,14.38964
1617089760000,8.352789,11.973950,14.85504,30.230410,35.190552,14.381060,6.640917,3.677806,46.613831,47.709621,...,18.024151,34.275002,2.081331,21.724461,25.227360,30.291439,30.543221,16.42481,21.177999,13.04684
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1617156120000,6.964218,10.489050,14.23991,24.617950,35.298309,14.411570,5.940909,3.483253,47.347221,47.709621,...,21.763559,34.340809,1.646449,21.166550,26.923019,29.270050,30.978100,14.39822,19.831390,13.14794
1617156180000,7.486839,11.623940,13.50462,28.409821,34.258789,15.894560,6.854543,3.295377,47.675289,47.709621,...,22.256620,34.323639,1.727512,21.000610,26.015110,28.900970,31.371019,14.91512,21.057831,13.35966
1617156240000,8.240253,9.448577,13.93664,26.277370,34.336041,14.877930,6.032464,3.018807,47.173649,47.709621,...,16.861601,33.859200,1.776150,20.989170,25.677500,30.198940,30.856991,15.54837,22.749670,15.45205
1617156300000,7.782483,11.812770,15.05436,27.170980,34.303612,14.310480,6.338598,3.128481,47.593269,47.709621,...,19.498550,33.763828,1.810483,19.575800,26.704620,29.194710,31.518841,15.19646,21.724461,15.06390
1617156360000,7.651827,11.203360,15.20123,27.949190,34.053749,17.235451,6.032464,3.374533,46.018730,47.709621,...,18.387501,34.396118,1.944953,20.913830,25.545891,27.567711,31.257530,15.12589,19.413670,14.07969

In [4]:
tag1=tags.get("id",39938)
tag2=tags.get("id",39939)

#EntityList of required tags
tag_list=EntityList("Tag")
tag_list.add(tag1)
tag_list.add(tag2)
tag_list_data = tag_list.data(start_time=1617086964262,stop_time=16170969642621)
print("Tag data of selected tags : ")
tag_list_data[0] #pandas df

Tag data of selected tags :

                  39938      39939
1617089520000  15.22221  28.349739
1617089580000  15.83638  27.278749
1617089640000  14.54509  27.082279
1617089700000  14.25994  25.977909
1617089760000  14.85504  30.230410
...                 ...        ...
1617341280000  14.25994  25.977909
1617341340000  14.85504  30.230410
1617341400000  15.48161  27.988291
1617341460000  15.03529  27.746050
1617341520000  16.64320  29.434080

[4010 rows x 2 columns]

### Batch

In [5]:
#EntityList of all batches of an asset
batches = asset1.batches()
print("First 5 batches from EntityList of all available batches of an asset : \n", batches[0:5])
print()

batch_at_index_0 = batches[0]
batch_at_index_1 = batches[1]

#EntityList of required batches
batch_list = EntityList("Batch")
batch_list.add(batch_at_index_0)
batch_list.add(batch_at_index_1)
print("\nbatch_list : ", batch_list)

First 5 batches from EntityList of all available batches of an asset :
 [<Batch: 11001_74553>, <Batch: 11002_74554>, <Batch: 11001_74555>, <Batch: 11002_74556>, <Batch: 11001_74557>]


batch_list :  <EntityList: [<Batch: 11001_74553>, <Batch: 11002_74554>, ]>

### Edge Connectors

In [6]:
#EntityList of all available edge_connectors
edge_connectors = client.edge_connectors()
print("All available edge connectors : \n", edge_connectors)
edge_connector_at_index_0 = edge_connectors[0]
edge_connector_at_index_1 = edge_connectors[1]


#EntityList of all tags of a specific edge_connector
ec_at_index_0_tags = edge_connector_at_index_0.get_tags()
print("\nFirst 5 tags from EntityList of all tags of an edge connector : \n", ec_at_index_0_tags[0:5])

#EntityList of required edge_connectors
ec_list = EntityList("EdgeConnector")
ec_list.add(edge_connector_at_index_0)
ec_list.add(edge_connector_at_index_1)
print("\nec_list : \n", ec_list)

#Get data of all tags of an edge_connector
ec_data = edge_connector_at_index_0.data(start_time=1617086964262,stop_time=161709696426)
print("\nec_data : ")
ec_data[0]

All available edge connectors :
 <EntityList: [<EdgeConnector: opcda-replay_730>, <EdgeConnector: batch asset replay_736>, <EdgeConnector: del_auto_abdf1_764>, ]>

First 5 tags from EntityList of all tags of an edge connector :
 [<Tag: name_1_39743>, <Tag: name_2_39744>, <Tag: name_3_39745>, <Tag: name_4_39746>, <Tag: name_5_39747>]

ec_list :
 <EntityList: [<EdgeConnector: opcda-replay_730>, <EdgeConnector: batch asset replay_736>, ]>

ec_data :

Empty DataFrame
Columns: [39975, 39743, 39744, 39745, 39746, 39747, 39748, 39749, 39750, 39751, 39752, 39753, 39754, 39755, 39756, 39757, 39758, 39759, 39760, 39761, 39762, 39763]
Index: []

[0 rows x 22 columns]

### Cotext Frames and ContextFrame Occurances

In [7]:
#EntityList of all available Context Frames
context_frames = client.context_frames()
print("EntityList of all available context Frames : \n", context_frames)

#EntityList of all occurences of a particular ContextFrame
cf_at_index_0 = context_frames[0]
cfo = cf_at_index_0.occurrences()
print("\nFirst 5 occurances from EntityList of all occurences of a ContextFrame : \n", cfo[0:5])

EntityList of all available context Frames :
 <EntityList: [<ContextFrame: 30>, ]>

First 5 occurances from EntityList of all occurences of a ContextFrame :
 [<ContextFrameOccurrence: 20606>, <ContextFrameOccurrence: 20815>, <ContextFrameOccurrence: 21149>, <ContextFrameOccurrence: 21009>, <ContextFrameOccurrence: 20993>]

In [8]:
cfo_at_index_0, cfo_at_index_1, cfo_at_index_2 = cfo[0], cfo[1], cfo[2]
#EntityList of specific ContextFrame Occurances
cfo_list = EntityList("ContextFrameOccurrence")
cfo_list.add(cfo_at_index_0)
cfo_list.add(cfo_at_index_1)
cfo_list.add(cfo_at_index_2)
print("EntityList of selected ContextFrame Occurances : \n", cfo_list)

EntityList of selected ContextFrame Occurances :
 <EntityList: [<ContextFrameOccurrence: 20606>, <ContextFrameOccurrence: 20815>, <ContextFrameOccurrence: 21149>, ]>

### Representation of an Entity

In [9]:
print("Name of Tag1 : ", tag1.name)
print("ID of Tag1   : ", tag1.id)
print("Tag1 Entity  : ", tag1)

print("\nEntities are generally represented in the following format : '<Name>_<ID>'")

Name of Tag1 :  UT-TV111
ID of Tag1   :  39938
Tag1 Entity  :  <Tag: UT-TV111_39938>

Entities are generally represented in the following format : '<Name>_<ID>'